#!/bin/bash

if [ "$1" == uninstall ]; then
    echo 'Desinstalando badvpn'
    rm /bin/badvpn && rm /bin/badvpn-udpgw
    echo 'Desinstalacion completa'
fi

if [ "$1" == start ]; then
    screen -dmS bad badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 1000 --client-socket-sndbuf 0 --udp-mtu 9000
    echo 'Badvpn iniciando en el puerto 7300'
fi

if [ "$1" == stop ]; then
    badvpnpid="$(ps x | grep badvpn | grep -v grep | awk '{print $1}')"
    if [ -n "$badvpnpid" ]; then
        kill -9 "$badvpnpid" >/dev/null 2>/dev/null
        kill "$badvpnpid" >/dev/null 2>/dev/null
        killall badvpn-udpgw
        echo 'Badvpn detenido'
    else
        echo 'Badvpn no esta en ejecucion'
    fi
fi

if [ "$1" == status ]; then
    badvpnpid="$(ps x | grep badvpn | grep -v grep | awk '{print $1}')"
    if [ -n "$badvpnpid" ]; then
        echo 'Badvpn esta en ejecucion (ON)'
    else
        echo 'Badvpn no esta en ejecucion (OFF)'
    fi
fi

if [ "$1" == help ]; then
    echo -e "\033[1;37mComandos:"
    echo -e "\033[1;31m badvpn start\033[1;37m para iniciar badvpn"
    echo -e "\033[1;31m badvpn stop \033[1;37m para parar badvpn"
    echo -e "\033[1;31m badvpn status \033[1;37m para ver el estado de badvpn (ON/OFF)"
    echo -e "\033[1;31m badvpn uninstall \033[1;37m para desinstalar badvpn"
fi
